/** 新增面板沿用 DSH 主题变量，不改宿主全局布局。 */
export const progressStyle = `
.dsh-test-recovery{font:inherit;font-size:12px;line-height:1.6;margin:8px 0;padding:10px 12px;border:1px solid var(--dsw-alias-state-error-primary,#be3b45);border-radius:6px;color:var(--dsw-alias-label-primary,#253041)}.dsh-test-recovery p{margin:6px 0}.dsh-test-recovery [role=alert]{color:var(--dsw-alias-state-error-primary,#be3b45)}.dsh-test-recovery details{margin:6px 0}.dsh-test-recovery code{overflow-wrap:anywhere}.dsh-test-recovery-confirm{border-top:1px solid var(--dsw-alias-border-l1,#e5e9ef);margin-top:9px;padding-top:9px}.dsh-test-recovery-confirm label{display:flex;align-items:flex-start;gap:6px}.dsh-test-recovery .dsh-test-actions button:disabled{opacity:.5;cursor:default;text-decoration:none}
.dsh-test-dock,.dsh-test-details{color:var(--dsw-alias-label-primary,#253041);font:inherit;font-size:12px;line-height:1.5}
.dsh-test-header{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;font:11px system-ui,sans-serif;padding:4px 6px;border:0;border-radius:4px;background:transparent;color:var(--dsw-alias-label-secondary,#64748b);cursor:pointer}.dsh-test-header:hover{background:var(--dsw-alias-interactive-bg-hover,#edf2f8)}.dsh-test-header span{color:var(--dsw-alias-link,#3873cf);font-variant-numeric:tabular-nums}
.dsh-test-dock{padding:10px 2px 8px;margin:6px 0;border-top:1px solid var(--dsw-alias-border-l1,#e5e9ef);animation:dsh-test-enter .18s ease-out}
.dsh-test-heading{display:flex;align-items:center;gap:8px;min-width:0}.dsh-test-heading strong{font-size:12px;font-weight:600}.dsh-test-heading .dsh-test-time{margin-left:auto;white-space:nowrap;color:var(--dsw-alias-label-secondary,#64748b);font-variant-numeric:tabular-nums}
.dsh-test-phase{color:var(--dsw-alias-link,#3873cf)}.dsh-test-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary,#64748b);margin:4px 0 8px}.dsh-test-actions{display:flex;gap:8px;align-items:center;margin-top:7px}.dsh-test-actions button{font:inherit;color:var(--dsw-alias-link,#3873cf);background:transparent;border:0;padding:3px 0;cursor:pointer}.dsh-test-actions button:hover{text-decoration:underline}.dsh-test-actions small{color:var(--dsw-alias-label-tertiary,#94a3b8);margin-left:auto}.dsh-test-actions a{color:var(--dsw-alias-link,#3873cf)}
.dsh-test-flow{display:flex;gap:12px;list-style:none;padding:0;margin:0;overflow-x:auto}.dsh-test-flow>li{flex:1;min-width:100px;position:relative;padding-top:4px}.dsh-test-flow>li:not(:last-child)::after{content:'';position:absolute;height:1px;background:var(--dsw-alias-border-l1,#dde3ec);top:14px;left:28px;right:-8px}.dsh-test-node{position:relative;z-index:1;width:20px;height:20px;display:grid;place-items:center;border-radius:50%;color:var(--dsw-alias-label-secondary,#64748b);background:var(--dsw-specific-menu,#f2f5fa);border:1px solid var(--dsw-alias-border-l1,#dde3ec);font-size:10px;transition:background .2s,color .2s,border-color .2s}.dsh-test-step-name{display:block;margin-top:5px;max-width:180px;line-height:1.45}.dsh-test-step-time{display:block;color:var(--dsw-alias-label-tertiary,#94a3b8);font-size:11px;font-variant-numeric:tabular-nums;margin-top:2px}.dsh-test-running .dsh-test-node{background:var(--dsw-alias-link,#3873cf);border-color:transparent;color:white;animation:dsh-test-pulse 1.8s ease-in-out infinite}.dsh-test-pass .dsh-test-node{color:var(--dsw-alias-link,#3873cf);border-color:var(--dsw-alias-link,#3873cf)}.dsh-test-error .dsh-test-node{color:var(--dsw-alias-state-error-primary,#be3b45);border-color:currentColor}.dsh-test-muted{color:var(--dsw-alias-label-tertiary,#94a3b8)}
.dsh-test-details{height:100%;overflow:auto;padding:18px 18px 24px}.dsh-test-details h2{font-size:15px;margin:0 0 10px;line-height:1.5}.dsh-test-details select{font:inherit;color:inherit;background:var(--dsw-specific-menu,#f6f8fb);border:1px solid var(--dsw-alias-border-l1,#dde3ec);padding:6px 8px;width:100%;margin:12px 0}.dsh-test-details .dsh-test-flow{display:block;overflow:visible}.dsh-test-details .dsh-test-flow>li{padding:0 0 20px 34px;min-width:0}.dsh-test-details .dsh-test-node{position:absolute;left:0;top:1px}.dsh-test-details .dsh-test-flow>li:not(:last-child)::after{left:10px;right:auto;top:26px;bottom:5px;width:1px;height:auto}.dsh-test-details .dsh-test-step-name{margin:0;max-width:none;font-size:13px}.dsh-test-checks{margin:7px 0 0;padding-left:16px;color:var(--dsw-alias-label-secondary,#64748b)}.dsh-test-checks li{padding:2px 0}.dsh-test-details details{border-top:1px solid var(--dsw-alias-border-l1,#e5e9ef);padding-top:10px;margin-top:10px}.dsh-test-details summary{cursor:pointer;color:var(--dsw-alias-label-secondary,#64748b)}.dsh-test-details details p{margin:8px 0}.dsh-test-reason{color:var(--dsw-alias-state-error-primary,#be3b45);margin-top:5px}.dsh-test-preview{height:100%;min-height:180px;display:flex;flex-direction:column;background:var(--dsw-specific-menu,#f6f8fb)}.dsh-test-preview iframe{width:100%;flex:1;min-height:0;border:0}.dsh-test-preview-message{margin:auto;padding:24px;text-align:center;color:var(--dsw-alias-label-secondary,#64748b);font-size:12px}
@keyframes dsh-test-enter{from{opacity:0;transform:translateY(3px)}to{opacity:1;transform:translateY(0)}}@keyframes dsh-test-pulse{50%{opacity:.65}}@media(prefers-reduced-motion:reduce){.dsh-test-dock,.dsh-test-running .dsh-test-node{animation:none}.dsh-test-node{transition:none}}
.dsh-test-settings{color:var(--dsw-alias-label-primary,#253041);font:inherit;font-size:13px;line-height:1.6;max-width:650px}.dsh-test-settings h2{font-size:18px;font-weight:600;margin:0 0 12px}.dsh-test-settings p{margin:8px 0 16px}.dsh-test-settings fieldset{border:0;padding:0;margin:20px 0}.dsh-test-settings fieldset>label{display:block;font-weight:500;margin:18px 0 7px}.dsh-test-settings input:not([type=checkbox]),.dsh-test-settings select{box-sizing:border-box;width:100%;padding:9px 10px;border:1px solid var(--dsw-alias-border-l1,#d6dde7);border-radius:6px;background:var(--dsw-specific-menu,#f6f8fb);color:inherit;font:inherit}.dsh-test-settings input:focus,.dsh-test-settings select:focus{outline:2px solid var(--dsw-alias-link,#3873cf);outline-offset:2px}.dsh-test-setting-switch{display:flex;align-items:center;gap:9px;font-weight:500}.dsh-test-setting-switch input{accent-color:var(--dsw-alias-link,#3873cf)}.dsh-test-settings .dsh-test-setting-hint{color:var(--dsw-alias-label-secondary,#64748b);font-size:12px;margin-top:6px}.dsh-test-setting-actions{display:flex;gap:10px}.dsh-test-setting-actions button{font:inherit;padding:8px 14px;border:1px solid var(--dsw-alias-border-l1,#d6dde7);border-radius:6px;background:transparent;color:inherit;cursor:pointer}.dsh-test-setting-actions button[type=submit]{background:var(--dsw-alias-link,#3873cf);color:white;border-color:transparent}.dsh-test-setting-actions button:disabled{opacity:.5;cursor:default}.dsh-test-settings [role=alert]{color:var(--dsw-alias-state-error-primary,#be3b45)}
`;
